export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const CATEGORY_CHANGE = 'CATEGORY_CHANGE';
export const LOADING = 'LOADING';
export const VIEW_TYPE_CHANGE = 'VIEW_TYPE_CHANGE';
export const CONTACT_CHANGE = 'CONTACT_CHANGE';
export const CONTACT_SEND = 'CONTACT_SEND';
export const CLEAR_RESPONSE = 'CLEAR_RESPONSE';
